# to activate/deactivate travisCI - go to https://travis-ci.org/, sign
# in with guthub, and follow instructions

language: python
python:
  - "2.7"

# before_install:
#   - "sudo apt-get build-dep python-scipy"

# install: travis_wait 60 "bin/bootstrap.sh $VIRTUAL_ENV"

script:
  - ./test.sh

notifications:
  email:
    - noah.hoffman@gmail.com
